from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
SAMPLE_DATA_DIR = DATA_DIR / "sample"

RANDOM_SEED = 42

NUM_LOCATIONS = 10
NUM_MACHINES = 100
NUM_PLAYERS = 5_000
NUM_SESSIONS = 20_000
NUM_TRANSACTIONS = 100_000
NUM_MACHINE_EVENTS = 15_000

START_DATE = "2025-01-01"
END_DATE = "2025-12-31"